dataconf:
  train_img_dir:   "/home/ning/data/NC2C_OxAAA_paired_160_160_128/train/labels"
  train_label_dir: "/home/ning/data/NC2C_OxAAA_paired_160_160_128/train/labels"

  val_img_dir:     "/home/ning/data/NC2C_OxAAA_paired_160_160_128/test/labels"
  val_label_dir:   "/home/ning/data/NC2C_OxAAA_paired_160_160_128/test/labels"
  
deviceconf:
  cuda_num: [0]
  
hyperparams:
  lr: 0.00001
  batch_size: 1
  epochs: 200
  embed_dim: 4

model_restore:
  ckpt_path: "/home/ning/projects/diff-3/src/lightning_logs/version_1"

ddconfig:
  double_z: true
  z_channels: 1
  resolution: [128, 128, 128]
  in_channels: 1
  out_ch: 1 # reconstructed scan
  ch: 32  
  ch_mult: [1, 2, 4, 4]  
  num_res_blocks: 2
  attn_resolutions: []
  dropout: 0.0

lossconfig:
  target: "losses.lpips.LPIPSWithDiscriminator"
  params:
    perceptual_weight: 1
    kl_weight: 0.000001 # 1e-6
    nll_mode: sum
    